cemiyet/cemiyet/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static
import posts.views
from . import views

urlpatterns = [
    path('', views.redirect_root, name='root'), #  Redirect
    path('content', posts.views.ContentView.as_view(), name='content'),
    path('posts', posts.views.PostsView.as_view(), name='posts'),
    path('ac/', posts.views.autocomplete, name='autocomplete'),
    path('tokens/', posts.views.tokens, name='tokens'),
    path('watch', posts.views.add_to_watchlist, name='watchlist'),
    path('admin/', admin.site.urls),
    path('accounts/login', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('reg/', include('tokens.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cemiyet/posts/urls.py
""" URLs pertaining to posts. """

cemiyet/posts/models.py
"""
Database models for posts.
"""

import os
import time
import django
from django.db import models
from django.conf import settings


#  Below is the code for AutoOneToOneField, copy pasted from the package
#  django-annoying. I found it redundant to include an entire package for one
#  class.
from django.db.models import OneToOneField
from django.db.transaction import atomic
try:
    from django.db.models.fields.related_descriptors import (
        ReverseOneToOneDescriptor,
    )
except ImportError:
    from django.db.models.fields.related \
            import SingleRelatedObjectDescriptor as ReverseOneToOneDescriptor

class AutoSingleRelatedObjectDescriptor(ReverseOneToOneDescriptor):
    """
    The descriptor that handles the object creation for an AutoOneToOneField.
    """

    @atomic
    def __get__(self, instance, instance_type=None):
        model = getattr(self.related, 'related_model', self.related.model)

        try:
            return (
                super().__get__(instance, instance_type)
            )
        except model.DoesNotExist:
            # Using get_or_create instead() of save() or create() as it better
            # handles race conditions
            obj, _ = model.objects.get_or_create(**{self.related.field.name: instance})

            # Update Django's cache, otherwise first 2 calls to obj.relobj
            # will return 2 different in-memory objects
            if django.VERSION >= (2, 0):
                self.related.set_cached_value(instance, obj)
                self.related.field.set_cached_value(obj, instance)
            else:
                setattr(instance, self.cache_name, obj)
                setattr(obj, self.related.field.get_cache_name(), instance)
            return obj

class AutoOneToOneField(OneToOneField):
    """
    OneToOneField creates related object on first call if it doesnt exist yet.
    Use it instead of original OneToOne field.

    example:

        class MyProfile(models.Model):
            user = AutoOneToOneField(User, primary_key=True)
            home_page = models.URLField(max_length=255, blank=True)
            icq = models.IntegerField(max_length=255, null=True)
    """

    def contribute_to_related_class(self, cls, related):
        setattr(
            cls,
            related.get_accessor_name(),
            AutoSingleRelatedObjectDescriptor(related)
        )
#  END OF AutoOneToOneField




class Tag(models.Model):
    """ A tag is just a word. """
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return str(self.name)

def assign_filename(instance, filename): #pylint: disable=W0613
    """ We save images with the filename replaced by the system time in
    nanoseconds. """
    temp = os.path.splitext(filename)
    return str(time.time_ns()) + temp[1]

class Post(models.Model):
    """ The central model of Djemiet. """
    title = models.CharField(max_length=255, blank=True)
    parents = models.ManyToManyField('self',
            related_name = 'children',
            symmetrical=False,
            blank=True)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    popularity = models.BigIntegerField(blank=False, null=False, default=0)
    image = models.ImageField(null=True, blank=True, upload_to=assign_filename)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
            on_delete=models.SET_NULL,
            blank=False,
            null=True)
    tags = models.ForeignKey(Tag,
            related_name = 'tagged_posts',
            on_delete=models.CASCADE,
            blank=True,
            null=True)
    descendants = models.IntegerField(blank=False, null=False, default=0)

    def __str__(self):
        return '#' + str(self.pk)

class Profile(models.Model):
    """ This follows the advice here:
    https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#extending-the-existing-user-model
    """
    user = AutoOneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=True)
    watchlist = models.ManyToManyField(Post, related_name= 'watched_by', blank=True)
    invited_by = models.ForeignKey(settings.AUTH_USER_MODEL,
            related_name='invitees',
            on_delete=models.SET_NULL,
            default=1,
            blank=True,
            null=True)

cemiyet/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}djemiet{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'normalize.css' %}" >
  <link rel="stylesheet" href="{% static 'skeleton.css' %}">
  <link rel="stylesheet" href="{% static 'djemiet.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Forum&family=Libre+Baskerville&family=Montserrat&display=swap" rel="stylesheet">
  <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/vollkorn" type="text/css"/>
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

cemiyet/templates/content.html
{% extends 'base.html' %}
{% load static %}
{% load post_filters %}
{% block content %}

{% include 'topbar.html' %}

<div id="contents">
    <div id="lightbox" onclick="close_lightbox()">
        <img id="lightboximg" src="">
    </div>

    <div id="focusdiv"></div>

    <div id="postingdiv">
        <button
            id="formswitch"
            class="button justified"
            onclick="toggle_form()">
            Create Post
        </button>
        {% include 'form.html' %}
    </div>

    <div id="carousel">

        <div id="leftnav" class="nav">
            <div class="arrow larrows" onclick="nav('1')"></div>
            <div class="arrow larrow" onclick="nav('prev')"></div>
        </div>

        <div id="gallerydiv">
        </div>

        <div id="rightnav" class="nav">
            <div class="arrow rarrow" onclick="nav('next')"></div>
            <div class="arrow rarrows" onclick="nav('total')"></div>
        </div>

    </div>
    <div id="bench"></div>
</div>

<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'jquery-ui.js' %}"></script>
<script src="{% static 'custom.js' %}"></script>
<script>
    $(document).ready( () => {
        query = JSON.parse('{{ query | escapejs }}');
        init_index(query);
    });
    $('#theform').on('submit', (e) => {
        e.preventDefault();
        submit_form();
    });
    $( function() {
        $(".taginput").autocomplete({
            source: '{% url 'autocomplete' %}',
        });
        $(".taginput").autocomplete('widget').css("z-index", "100");
        $('#tagfilter').on('autocompleteselect', add_tag_from_autocomplete);
    } );
</script>
{% endblock content %}

cemiyet/templates/form.html
<div id="formdiv" class="shadow-white">
    <div class="titlebar">
        <div class="widget montserrat"
             onclick="clear_form()">Ø</div>
        <div class="title">CREATE NEW POST</div>
        <div class="widget montserrat"
             onclick="toggle_form()">X</div>
    </div>
    <div class="formfields">
        <form id="theform" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <input type="text"
                   placeholder="Subject"
                   id="id_title"
                   name="title">

            <div id="uploaddiv">
                <div id="filelabel"
                     class="button"
                     onclick="$('#id_image').click()">
                    ⇧
                </div>
                <span id="filename">No image selected.</span>
                <input class="submitfile"
                       type="file"
                       name="image"
                       accept="image/*"
                       onchange="update_filename()"
                       id="id_image">
            </div>

            <label for="id_body"></label>

            <div>
                <textarea class="largetextbox"
                          name="body"
                          cols="25"
                          rows="40"
                          required=""
                          placeholder="Post body"
                          id="id_body"
                          ></textarea>
            </div>

            <div>
            <input type="text"
                   name="tag_text"
                   class="taginput"
                   id="tag_text"
                   placeholder="Tag">
            </div>

            <div id="formerrordiv"></div>

            <button class="button nomargin" type="submit">Post</button>

        </form>
    </div>
</div>

cemiyet/templates/topbar.html
{% load static %}
<div id="topbar" class="shadow-white">
    <div id="topbar-logo"
         style="cursor: pointer" onclick="home()"></div>
    <div id="favtoggle" onclick="toggle_favfilter()"></div>
    <input id="tagfilter" class="taginput" type="text" placeholder="Tag filter">
    <div id="taglist">
    </div>
    <div id="cleartagsbox">
        <div id="cleartags"
             class="leftmost fineprint corner-widget"
             onclick="clear_tags_click()">Ø</div>
    </div>
    <div id="tokenboxplaceholder">
        <div id="tokenbox">
            <div id="tokenpopup">
                <div class="titlebar">
                    <div class="title">REGISTRATION LINKS</div>
                    <div class="widget montserrat"
                         onclick="$('#tokenpopup').hide();">X</div>
                </div>
                <div id="tokenlist"></div>
            </div>
        </div>
    </div>
    <a id="logout" class="button" href="{% url 'logout' %}"></a>
</div>